export const FETCH_INITIAL_SURVEY_DATA = 'FETCH_INITIAL_SURVEY_DATA';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const SHOW_SUCCESS_PAGE = 'SHOW_SUCCESS_PAGE';

export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

export const UPDATE_VALIDATION_ERRORS = 'UPDATE_VALIDATION_ERRORS';
export const CLEAR_VALIDATION_ERRORS = 'CLEAR_VALIDATION_ERRORS';


// API
export const API_SURVEY_URL = '/api/v1/survey';
export const GET_INIT_DATA = '/api/v1/survey';